server:
  port: 8089

spring:
  datasource:
    #别名
    sqlserver:
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      url: jdbc:sqlserver://192.168.200.24\SQL2012YPT3;databaseName=YYGH
      url: jdbc:sqlserver://127.0.0.1\SQLSERVER;databaseName=school
      username: sa
      password: 123qwe,.
    #别名
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/school
      username: root
      password: 123456



